### ISSUE TITLE
Look more into `Modifier.simpleVerticalScrollbar` possible source for scroll lagg

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1202]

**Comment by MV-GH** [comment]
[app-debug_zoomable.zip](https://github.com/dessalines/jerboa/files/12527348/app-debug_zoomable.zip)
[app-release_zoomable.zip](https://github.com/dessalines/jerboa/files/12527349/app-release_zoomable.zip)

**Comment by dessalines** [comment]
can re-open if necessary.

**Comment by MV-GH** [comment]
Yes, it was mostly reminder for when I have some extra time.

**Comment by MV-GH** [comment]
I spent a huge time in #1431 investigating and fixing recompositions.

One of the biggest sources was this. I should looked deeper into this hunch that I had.

Gutted Jerboa version with scrollbar modifier:

https://github.com/LemmyNet/jerboa/assets/67873169/f741cb68-4267-4bf0-a63c-180d6ebc863e


Gutted Jerboa version without scrollbar modifier:


https://github.com/LemmyNet/jerboa/assets/67873169/8e79567d-31e3-438e-9d62-ca004ba6ce15

**Comment by dessalines** [comment]
I'm 100% in favor of removing our custom scrollbar then, and waiting for google to add a proper one to jetpack compose.

**Comment by MV-GH** [comment]
Builtin Compose scrollbars are still in the backlog
https://developer.android.com/jetpack/androidx/compose-roadmap

**Comment by dessalines** [comment]
What do you think? I'd still be in favor of removing our custom one until jetpack compose adds theirs.

**Comment by MV-GH** [comment]
I was planning on removing it for the feeds where scroll lagg is noticable
