### ISSUE TITLE
Profile comments scroll momentum is not cancelled

### ISSUE THREAD

**Issue by bappitybup** [LemmyNet/jerboa#1259]
### Jerboa Version

0.0.49

### Android Version + Phone

Android 14, Pixel 7 Pro and Pixel 8 Pro

### Describe The Bug

in the profile comments tab, scrolling down and letting go (letting the momentum finish the scrolling) and then immediately trying to scroll up will not cancel the momentum of the previous, causing a stutter.

### To Reproduce

1. Navigate to profile page
2. Navigate to comments tab in profile page
3. Make sure there are enough comments to be scrolled through 
4. scroll down and let go
5. While scroll momentum is still present, try to scroll upwards
6. Witness stutter

VIDEO:
[https://drive.google.com/uc?export=download&id=1-s2rBBzVakixuBPwquT_BjuE5L_PmxXT](https://drive.google.com/uc?export=download&id=1-s2rBBzVakixuBPwquT_BjuE5L_PmxXT)

**Comment by bappitybup** [comment]
still affects 0.0.53

**Comment by MV-GH** [comment]
Yeah its annoying but not sure how to fix this, seems like a issue with compose

Only happens with tabs + actionbar that hides when scrolls

**Comment by MV-GH** [comment]
I can nolonger reproduce this with the current master. Next release should fix this.

https://github.com/LemmyNet/jerboa/assets/67873169/9089aad8-4275-4626-8370-850ed4d8b7a7

*66 vs master*
