### ISSUE TITLE
Get rid of `material` use material3

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1433]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Long term, I want to completely get rid of material and only have material3 in the dependencies

List the blockers here:
- ~~accompanist-pager~~
- ~~swipeToDismiss~~ (deprecated one)
- ~~Alorma~~
- ~~PullRefreshIndicator, possible replacement that is experimental~~ [pulltorefresh](https://developer.android.com/reference/kotlin/androidx/compose/material3/pulltorefresh/package-summary)

**Comment by MV-GH** [comment]
All these are removed. Ig its just icons that have a dependency on material

**Comment by dessalines** [comment]
Nice, we can probably close then.
