### ISSUE TITLE
Saved comments, empty space in header does nothing

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1469]
### Jerboa Version

0.0.65

### Android Version + Phone

n/a

### Describe The Bug

Header in the saved comments, empty space does nothing. Expect it to open the post. This would be inline with other headers.

### To Reproduce

go to save comment
press on the header empty space (title does behave as expected)

https://github.com/MV-GH/LemmyBackwardsCompatibleAPI/assets/67873169/62d7f6d4-be1e-4f71-94dd-6954e090379d

**Comment by dessalines** [comment]
Might be good to have a different mode for the comments, maybe called `flat` or `nonThreaded`, so it behaves differently from screens where comments are viewed in the non-threaded way.

**Comment by MV-GH** [comment]
![image](https://github.com/LemmyNet/jerboa/assets/67873169/d4658e66-bab0-4305-abb6-b432313a8704)
it seems that already exists
