### ISSUE TITLE
where do you go to dispute a ban / get your data after a ban

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/jerboa#1474]
i feel like this should be an in-app feature to message mods when this happens and be presented wirh your mod log

**Comment by MV-GH** [comment]
If you are instance banned, I doubt you can message the admins. So this will need a change at Lemmy

@dessalines

**Comment by RustoMCSpit** [comment]
> For community bans, we are unable to be notified so that isn't possible either.

that can be implemented

**Comment by MV-GH** [comment]
Once that feature is implemented, yes.  https://github.com/LemmyNet/lemmy/issues/4572

**Comment by dessalines** [comment]
Yes, this would end up eventually in your notifications / inbox. We're really far away from that tho, and it still isn't a ban dispute system: nothing like that exists in Lemmy.
