### ISSUE TITLE
0.19.4-beta.2 removal of public_key in /api/v3/site results in failing jerboa

### ISSUE THREAD

**Issue by ticoombs** [LemmyNet/jerboa#1476]
### Jerboa Version

0.0.65

### Android Version + Phone

Android 14

### Describe The Bug

public_key was removed from 0.19.4-beta.2 as such jerboa classes it as an account failure and marks the accounts as "not in a ready state yet". 

![Screenshot_20240409-085817](https://github.com/LemmyNet/jerboa/assets/2687896/d1b5a4a7-38e6-4cc7-ac08-053fb0c9c4a5)

### To Reproduce

1. Update server to 0.19.4-beta.2
2. Account is now basically unusable due to requirements of public_key

### In the case of a crash or when relevant include the logs

N/A (no logs as it technically doesn't "crash")

**Comment by souperk** [comment]
Leaving the full message in the text, so this issue appears on search engines:

```
Illegal input: Field `public_key` is required for type with serial name 'it.vercruysse.lemmyapi.v0x19.datatypes.site', but it was missing at path $.site_view.site
```

**Comment by dessalines** [comment]
Removing that field has been reverted in Lemmy's back-end now, I'll try to deploy it on voyager.lemmy.ml sometime soon. 

Also tho, @MV-GH  updated a dependency removing that field requirement anyway, so this should be fixed.
