### ISSUE TITLE
Many Illegal input erros after last update

### ISSUE THREAD

**Issue by dev0T** [LemmyNet/jerboa#1478]
### Jerboa Version

0.0.66

### Android Version + Phone

Android 14

### Describe The Bug

After the last update, many "Illegal input" errors pop up.

![image](https://github.com/LemmyNet/jerboa/assets/28127196/2ea4787b-0e02-4103-9220-daa903b3555a)

### To Reproduce

1. Open the app

**Comment by MV-GH** [comment]
Which instance? That is not a change in Jerboa but rather in Lemmy. I am unaware of any breaking API changes

**Comment by MV-GH** [comment]
That field still exists in the latest alpha of 0.19.4 , voyager works on Jerboa. I believe this a custom change by your instance.

**Comment by MV-GH** [comment]
I'll be closing this unless I receive more information.
