### ISSUE TITLE
Replace Swipeable with AnchoredDraggable

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1479]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

This is the last part of the deprecated code, since upgrading to the latest Compose

It is also on the blockers for removing material  #1433

https://developer.android.com/develop/ui/compose/touch-input/pointer-input/migrate-swipeable

**Comment by dessalines** [comment]
cc @Snow4DV

**Comment by MV-GH** [comment]
That code wasn't written by Snow, but by someone else see. its the swipeToNavigateBack

f54582cfa33c7ffbe2530786740126371454804c

**Comment by dessalines** [comment]
Ah my bad.
