### ISSUE TITLE
change show bot accounts to show bot posts and show bot comments or allow a toggle

### ISSUE THREAD

**Issue by coelacanthfucker420** [LemmyNet/jerboa#1481]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

I love that I can filter bot posts because i dont like seeing reddit repost bots but some bots such as the ones the posts alternative links to youtube videos and the like can be very helpful and I wish I was able to see those while still filtering bot posts.

**Comment by MV-GH** [comment]
If you are talking about the usersetting show bot accounts. This a Lemmy feature, thus enhancement for this feature will need to be proposed at the Lemmy repo.

**Comment by dessalines** [comment]
Yep, this already exists in jerboa. Go into your account settings, scroll down, show bot accounts.
