### ISSUE TITLE
"The instance us experiencing interneal issues" causes jerboa to break

### ISSUE THREAD

**Issue by Aipathon** [LemmyNet/jerboa#1488]
### Jerboa Version

0.0.66

### Android Version + Phone

Android 11 LG K61

### Describe The Bug

When opening the app I regularly get the error message "The Instance Feddit.de is experiencing internal server errors". This causes the App to effectively become unusable. This means: Accessing profile, voting,commenting or accessing notifications is not possible(I only get an error showing "This account is not in a ready state yet"). When leaving a comment section the whole feed reloads. This bug is also not an issue caused by my instance, since other users did not have the same issue on other apps. Other Jerboa users experienced the same problem.

The bug can usually be fixed by clearing the cache or app data, but this doesn't always work.

### To Reproduce

1. Open Jerboa
2. See error

**Comment by MV-GH** [comment]
Can you reach instance from the browser at those times? I just checked and it returns 504 now. 

Jerboa does a few things, on startup it needs to retrieve SiteSettings. Those contain your settings and your account info, other stuff Jerboa needs. When it fails to do so. It will follow a recovery/verification procedure. Is this instance "alive", is the auth still alive,...

In this case, it failed at is the instance alive check. 

So it notifies you about this. Each time you do any of those actions. It will retry the steps and display if it fails.

Jerboa can't do anything if it can't connect or authenticate. So this behaviour is expected. Unless you desire something else?

**Comment by Aipathon** [comment]
> Can you reach instance from the browser at those times? I just checked and it returns 504 now. 
> 
> Jerboa does a few things, on startup it needs to retrieve SiteSettings. Those contain your settings and your account info, other stuff Jerboa needs. When it fails to do so. It will follow a recovery/verification procedure. Is this instance "alive", is the auth still alive,...
> 
> In this case, it failed at is the instance alive check. 
> 
> So it notifies you about this. Each time you do any of those actions. It will retry the steps and display if it fails.
> 
> Jerboa can't do anything if it can't connect or authenticate. So this behaviour is expected. Unless you desire something else?

Feddit.de currently has some problems. The web frontend is completely broken and images don't work, since the server itself has some stuff with the image box(idk what exactly broke). The API and the entire Backend however should still be intact.

**Comment by MV-GH** [comment]
From a cursory look the API seems to work although the auth may fail, I have not tested it. Mostly likely it fails the verification procedure because the the domain doesn't return 200. I may tweak this so that it will only do it if the site fails but will have to see how easily this can be done.

**Comment by Aipathon** [comment]
That would be very nice if you could fix this :)

**Comment by dessalines** [comment]
feddit.de is giving a server error when I try to access it anyway. Do you get this issue with any working lemmy server?

**Comment by Aipathon** [comment]
@dessalines I will try it out with another instance, but it might take some time, since the error doesn't appear in regular Intervals.

**Comment by Aipathon** [comment]
@dessalines it seems like it is an issue related to feddit.de. I found out, that when I log out of my account(and therefore then use Lemmy.world) the issue instantly dissapears.

**Comment by MV-GH** [comment]
To confirm you only have this when feddit is your active/current selected account? 

You should not be experiencing this while you have a different account selected.
