### ISSUE TITLE
Support alt-text field for post images.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/jerboa#1513]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

All images that aren’t decorative need a text alternative, so that people using screen readers can hear what the image or icon means. This might be hard to implement as there is much user generated content. Perhaps you could provide an option to your users to add text descriptions to their uploads, and encourage them to do so.

**Comment by MV-GH** [comment]
I think this was added to Lemmy? Alt text, doesn't seem like a huge change needed to support this.

**Comment by dessalines** [comment]
Yep it was, I'll be adding a lot of these new `0.19.4` features in the next few weeks.
