### ISSUE TITLE
Votes are gone in listingmode

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1541]
This is because listingmode only show scores. For versions before 0.19.4 This is now always false since we don't use the old show_version option. #1544  Fixes this for old versions.

For new 0.19.4 this problem will still exist if the user decides to hide show_scores.
I think we should show one of the other options? @dessalines  what do you think?

![IMG_20240608_145650.jpg](https://github.com/LemmyNet/jerboa/assets/67873169/ee89af00-159b-4949-8c54-d6ec08a2174f)

**Comment by dessalines** [comment]
This should be solved by your #1544 , which inserts the older show_scores for versions < 0.19.4
