### ISSUE TITLE
When viewing the subscribed feed, paging is broken

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/jerboa#1596]
### Jerboa Version

0.0.70

### Android Version + Phone

all

### Describe The Bug

Paging seems to be broken only when viewing the subscribed feed. *Posts loading failed*

All and local seem to be working fine.

Context : https://biglemmowski.win/comment/4199437

cc @MV-GH 

### To Reproduce

- Click your subscribed feed
- Scroll down
- See error, no more posts load.

### In the case of a crash or when relevant include the logs

Na

**Comment by MV-GH** [comment]
I ll take a look and see if i can see anything in the logs

**Comment by MV-GH** [comment]
Hmm I don't see anything wrong?

```
00:51:32.277  D  REQUEST: https://lemmy.one/api/v3/post/list?type_=Subscribed&sort=Hot&page=2&page_cursor=P1019081
                 METHOD: HttpMethod(value=GET)
                 COMMON HEADERS
                 -> Accept: application/json
                 -> Accept-Charset: UTF-8
                 -> Authorization: ***
                 -> User-Agent: Jerboa
                 CONTENT HEADERS
                 -> Content-Length: 0
                 BODY Content-Type: null
                 BODY START
                 
                 BODY END
00:51:32.473  D  RESPONSE: 400 
                 METHOD: HttpMethod(value=GET)
                 FROM: https://lemmy.one/api/v3/post/list?type_=Subscribed&sort=Hot&page=2&page_cursor=P1019081
                 COMMON HEADERS
                 -> access-control-expose-headers: vary, content-encoding, content-type
                 -> alt-svc: h3=":443"; ma=86400
                 -> cache-control: private
                 -> cf-cache-status: DYNAMIC
                 -> cf-ray: 8a3d5157492959e3-MXP
                 -> content-type: application/json
                 -> date: Mon, 15 Jul 2024 22:51:32 GMT
                 -> server: cloudflare
                 -> strict-transport-security: max-age=31536000; includeSubDomains; preload
                 -> vary: accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
                 BODY Content-Type: application/json
                 BODY START
                 {"error":"couldnt_get_posts"}
                 BODY END
```

Why does it throw 400 ?

**Comment by MV-GH** [comment]
Oh this is why 
![image](https://github.com/user-attachments/assets/ccbfcea4-b68a-42b1-a81a-0f494e28796d)

**Comment by dessalines** [comment]
Nice catch, so we gotta remove the page (maybe only for 0.19.0 and later)

**Comment by MV-GH** [comment]
I have this already fixed for 0.19.0-2 But I forgot to include this fix in 0.19.3-5

**Comment by nicolasnobelis** [comment]
I am experiencing this issue again with the version 0.0.77 from F-droid.

How can I get the application logs to open an issue ?

**Comment by MV-GH** [comment]
Can you share some more info? Which instance do you experience this?

**Comment by nicolasnobelis** [comment]
There is nothing more in the steps to reproduce as what you described: changing the values in the drawer and seeing the bug happen on all but "local".

Thanks for the fast answer anyway. I will experiment a bit more and open an issue if needed.

**Comment by MV-GH** [comment]
Okay, no problem. Maybe one more thing, can you verify the version by going settings > about > at the top.

**Comment by nicolasnobelis** [comment]
`0.0.77-gplay`
