### ISSUE TITLE
Can't log in to lemmy.world despite it working on the browser

### ISSUE THREAD

**Issue by DigitalNaut** [LemmyNet/jerboa#1625]
### Jerboa Version

0.0.71

### Android Version + Phone

Android 11

### Describe The Bug

I've been unable to log into lemmy.world on the app for the past two days despite the site being up and running perfectly on desktop and mobile browsers.

Whenever I select the server and type in my credentials, the app attempts to sign in but it times out eventually. This does not happen with lemmy.blahaj.zone or lemmy.dbzer0.com which I've tested out successfully. Perhaps lemmy.world's sign-in process has changed?

I've turned off all my ad-blocking software just in case and still no luck.

![Screenshot](https://github.com/user-attachments/assets/1b5abd5c-0efa-4e2a-b12a-b10bbac68e53)

### To Reproduce

1. Click on Add Account
2. Select lemmy.world from the dropdown & type in the correct credentials (copied & pasted from my password manager)
3. Click login & wait

**Comment by MV-GH** [comment]
Hmm, I can't reproduce this.

**Comment by DigitalNaut** [comment]
I thought that maybe clearing the cache and storage would work and it did. Very strange. Thanks for taking the time to look into this anyway!

**Comment by MV-GH** [comment]
I don't think that is related. It was probably lemmy.world that was experiencing some transient errors.
