### ISSUE TITLE
Legacy show scores behaviour is not correct

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1626]
### Jerboa Version

rework ui

### Android Version + Phone

m/a

### Describe The Bug

If legacy show scores is false it must hide all scores. Which it doesn't do atm

### To Reproduce

1 -> use instance that is pre 0.19.4
2 -> disable show_scores
3 -> still see scores

**Comment by dessalines** [comment]
I think I know where I introduced this one, I'll get it.
