### ISSUE TITLE
List view scores not like before

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1627]
### Jerboa Version

ui rework

### Android Version + Phone

n/a

### Describe The Bug

![image](https://github.com/user-attachments/assets/8d35f715-a917-4426-8cba-f4a69bfd08ef)

This does not look well for listview.

### To Reproduce

change postviewmode to listview

**Comment by dessalines** [comment]
This was part of moving the vote info back into the `VoteGeneric` composables. I suppose for the list view we could add a `forceHide = false` param. 

Should we just show upvotes in between the two voting bars like before?

**Comment by MV-GH** [comment]
Yes, previous behaviour is great

**Comment by dessalines** [comment]
Cool, when I get back from vacation I'll be able to fix it.
