### ISSUE TITLE
Markdown rending subtext 

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/jerboa#1628]
### Jerboa Version

0.0.71

### Android Version + Phone

N/a

### Describe The Bug

![image](https://github.com/user-attachments/assets/aeaf4604-ecf5-4d67-b5b9-d1064359c7e7)

![image](https://github.com/user-attachments/assets/0b185986-5cb5-4299-bdea-2435197ea0ef)

This should not be formatted as subtext. But it is following the current spec in Jerboa. Which is any text between a tilde that is uninterrupted by a linebreak becomes subscript.

There doesn't seem to be a commonmark spec to follow?

What does Lemmy UI do?

### To Reproduce

- this text

```
Been driving an EV for 6 years now. Tesla model X (range ~ 260kms) first, now a model Y LR (range ~ 480kms)
```

**Comment by dessalines** [comment]
Part of that `ScriptRewriteSupportPlugin`. We need to look at how other markwon projects are adding super / subscript support.

**Comment by MV-GH** [comment]
We just need a better definition. I don't if lemmy follows an exact spec for sup/subscript. Noties follows the <sub> syntax which is the most popular way.

**Comment by dessalines** [comment]
Here's everything we try to support: https://join-lemmy.org/docs/users/02-media.html?highlight=markdown#text

I think we're following reddits style of super / subscript.

**Comment by MV-GH** [comment]
I can make the subscript definition more strict to prevent the above example for being picked up. By not allowing whitespace.

The definition becomes:

Any text between a tilde that is not interrupted by a linebreak where the starting or ending text can't be a whitespace character.

According to this https://www.markdownguide.org/tools/reddit/

reddit does not support subscript. Lots of markdown implementations use \~text\~ instead for strikethrough like Github.
