### ISSUE TITLE
Search: all instance posts

### ISSUE THREAD

**Issue by jujubeja** [LemmyNet/jerboa#1629]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

**Is your feature request related to a problem? Please describe.**
As user
I want to add multiple instances of lemmy
So that you can view posts from all instances that do not follow each other

**Describe the solution you'd like**

Enable full instance search
https://lemmy.world/search?q=%s
https://lemm.ee/search?q=%s

Load List: import instance list by url .txt and .toml and .json
```
https://raw.githubusercontent.com/LemmyNet/jerboa/main/instances.toml
https://github.com/LemmyNet/jerboa/blob/main/instances.toml
```

**Additional context**
full instance list
https://data.lemmyverse.net/
https://lemmy.fediverse.observer/list

**Comment by dessalines** [comment]
Lemmy doesn't have an instance-specific filter, so that would need to get added first.

Post search should be part of #27
