### ISSUE TITLE
Multiplatform support iOS and Android platform

### ISSUE THREAD

**Issue by zoujiaqing** [LemmyNet/jerboa#1640]
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Can support for iOS platform? thank u.

Now, Kotlin 2.0 can both run iOS and Android platform.

**Comment by dessalines** [comment]
Dupe of #649
