### ISSUE TITLE
Buttons navbar gone with .72 update

### ISSUE THREAD

**Issue by rottenwheel** [LemmyNet/jerboa#1648]
Might be just me but I lost the navbar with home, search, notifications. If you squint enough in the screenshot it looks like it is simply cut off but a tiny bit left, so you can see. I tried tapping on the third of a button that I get to see, but they don't work, or some do, but super hard to tap on. Not enough button. 😁

![](https://lemmy.zip/pictrs/image/cc235380-9d84-45c1-8f56-48a75c319502.webp)

**Comment by MV-GH** [comment]
Which android version?

Definitely related to #1607

**Comment by sanatsathaye** [comment]
+1 for this. Pixel 7 running Android 14.

**Comment by MV-GH** [comment]
Hmm I can't actually reproduce this on Android 14.

**Comment by sanatsathaye** [comment]
Experimented with settings a bit. It's normal with "Show text descriptions in navigation bar" in Look and Feel settings turned on. But when that setting is off it looks like that.

**Comment by MV-GH** [comment]
I can reproduce this now. Thanks! It doesn't only happen on Android 14.

**Comment by MV-GH** [comment]
> For me it was the opposite. I guess I had it disabled prior to update; enabling the show text thing, fixed it. Now I get navbar buttons. Funny how for you it is the opposite.

I think that's what he is saying? Else my fix isn't going to work D:
