### ISSUE TITLE
Card display mode obscures navigation and top system bar(time, batt, etc)

### ISSUE THREAD

**Issue by Stugist** [LemmyNet/jerboa#1654]
### Jerboa Version

0.0.72

### Android Version + Phone

13, SM-G781B/DS

### Describe The Bug

When in Big card display mode top system bar is obscured, and bottom navigation bar is sometimes mostly cut off.

Switching display modes seems to fix the navigation bar, but not the top system bar. 

### To Reproduce

1 settings
2 card
3 ?

**Comment by MV-GH** [comment]
Can you post a screenshot. It's not very clear to me

**Comment by MV-GH** [comment]
U sure its not the bug where your status bar icons have the same color as the background?

**Comment by Stugist** [comment]
> U sure its not the bug where your status bar icons have the same color as the background?

Could be, I now cannot recreate the issue, I suppose feel free to close the issue for now as it seems to be unreproducable. Or keep it open and knock it to lowest priority and I'll update with screenshots/caps if it happens again.

**Comment by MV-GH** [comment]
I'll reopen this issue if you can reproduce it.
