### ISSUE TITLE
Show parent comment navigation buttons doesn't work

### ISSUE THREAD

**Issue by n2burns** [LemmyNet/jerboa#1655]
### Jerboa Version

0.0.72

### Android Version + Phone

Android 12, Samsung Galaxy S10e

### Describe The Bug

Toggle for "Show parent comment navigation buttons" doesn't do anything. I tried changing a bunch of other settings without luck. I even rolled back to 0.0.71 to check, and it works fine in the old version.

### To Reproduce

Go to "Settings" -> "Look and feel" -> turn on "Show parent comment navigation buttons".

Expected Behaviour: In posts, two buttons (up and down arrows) should appear to allow for navigation between comments.
(Picture from 0.0.71)
![Screenshot_20240904-203012_Jerboa](https://github.com/user-attachments/assets/0dcfd402-ce65-4130-9c1e-4ee5d4385038)

Actual Behaviour: The buttons do not appear.
(Picture from 0.0.72)
![Screenshot_20240904_203049](https://github.com/user-attachments/assets/2a1b8efe-1675-42f9-830e-737e84f99e4a)

**Comment by MV-GH** [comment]
Related #1607
