### ISSUE TITLE
Backspace swipe delete gesture leads to additional deleted characters on subsequent 'backspace' input

### ISSUE THREAD

**Issue by Vikingtons** [LemmyNet/jerboa#1707]
### Jerboa Version

0.0.77

### Android Version + Phone

Android 14, Google Pixel 7

### Describe The Bug

There appears to be a minor quirk with the text compose field when using gesture input keyboards like [Heliboard](https://github.com/Helium314/HeliBoard).

It seems that input is repeated when using the back space button after leveraging the swipe-to-delete gesture on the same button to clear multiple characters.

Tapping the button after leveraging this gesture seems to incorrectly delete multiple characters (approx the length of string previously deleted by the gesture) instead of just one.

Here's a video to demonstrate:
https://github.com/user-attachments/assets/8a3e992d-5f75-4e84-a9dc-3d4e12c36757

This only occurs in Jerboa, it doesn't appear to occur in other apps:
https://github.com/user-attachments/assets/1b533932-5be1-4171-b00b-10a477cc896b

There was a similar issue with Element X android + Heliboard / Gboard some time ago, which was somehow related to their message composer. I'll try to find the ticket in case it contains any relevant info.

### To Reproduce

1. Install [Heliboard](https://github.com/Helium314/HeliBoard/releases) (please also grab the [sliding input library](https://github.com/erkserkserks/openboard/tree/46fdf2b550035ca69299ce312fa158e7ade36967/app/src/main/jniLibs/arm64-v8a) and install via Settings > Advanced > Experimental > Load gesture typing library), [Futo Keyboard](https://github.com/futo-org/android-keyboard/releases) or [Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin&hl=en-US)
2. Open Jerboa
3. Tap to create a new post, or attempt to comment on an existing one
4. Create an arbitrary sting of text in a field
5. Slide across the backspace button to delete a selection of text
6. Tap the back space button and observe that an additional selection of text is deleted instead of just one character
7. Switch to another app, such as Signal, Element X Android, StandardNotes etc.
8. Repeat steps 4-6 and observe result

**Comment by MV-GH** [comment]
Sounds like #194

**Comment by Vikingtons** [comment]
That does indeed seem relevant. Sorry, I did try to skim the backlog but I couldn't think of the right search terms to articulate the issue. I could have just used 'backspace' in hindsight.
