### ISSUE TITLE
Incorrect posts when opening Jerboa from another app

### ISSUE THREAD

**Issue by hunkyburrito** [LemmyNet/jerboa#905]
**Jerboa Version**
0.0.36

**Android version + phone**
Android 12
Samsung Galaxy S10

**Describe the bug**
Using the "open in app" button from firefox to open a community in Jerboa leads to strange results:

Expected results:
![Screenshot_20230628-141008_Jerboa for Lemmy.png](https://github.com/dessalines/jerboa/assets/48025161/57392282-823a-4007-ad37-faab315a677a)

Actual Results:
![Screenshot_20230628-141110_Jerboa for Lemmy.png](https://github.com/dessalines/jerboa/assets/48025161/39f74293-5f45-4bbc-97ca-c00724e43527)

Seems like it is recognizing the community info but it doesn't load the correct posts.

**To Reproduce**

1. Go to a community page on a browser.
2. Launch Jerboa from the browser

**Comment by MV-GH** [comment]
I think this is related to #1050
